git:
  submodules: false

language: latex

addons:
  apt:
    packages:
      - make
      - python
      - python-sympy
      - graphviz
      - texlive-base
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-science

# sympy ends up in /usr/lib/python2.7/dist-packages, which is not part of the
# default python path.
script:
  - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages make
  - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages make chisel
  
